# Knowledge Discovery in Databases
## Fase de transformação dos dados

Nesta fase é feita a transformação dos dados, de forma que fiquem em conformidade com os padrões exijidos pelo algoritmo de mineração de dados.
Neste estudo de caso, será utilizado o algoritmo Apriori para mineração de regras de associação.
Para este tipo de técnica, é preferível que a base de dados contenha dados qualitativos, ou seja, que o dado seja uma característica, e não quantitativas, apenas numéricos.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('alunos_categoria_administrativa.csv', sep='|')

#### Transformando os atributos nominalmente

#### Turno

In [5]:
df['TP_TURNO'] = df['TP_TURNO'].apply(lambda x: 'matutino' if x==1.0 else('vespertino' if x == 2.0 else('noturno' if x == 3.0 else('integral' if x == 4.0 else('EaD')))))

#### Data de ingresso para Ano Ingresso

In [6]:
df['DT_INGRESSO_CURSO'] =  pd.to_datetime(df['DT_INGRESSO_CURSO'], format='%d/%m/%Y')
df['ANO_INGRESSO'] = df['DT_INGRESSO_CURSO'].dt.year

#### Criando IDADE_INGRESSO

In [9]:
df['IDADE_INGRESSO'] = df['ANO_INGRESSO'].sub(df['NU_ANO_NASCIMENTO'])

In [10]:
df

,TP_CATEGORIA_ADMINISTRATIVA,TP_ORGANIZACAO_ACADEMICA,TP_TURNO,TP_GRAU_ACADEMICO,TP_COR_RACA,TP_SEXO,NU_ANO_NASCIMENTO,NU_MES_NASCIMENTO,NU_DIA_NASCIMENTO,DT_INGRESSO_CURSO,IN_RESERVA_ETNICO,IN_RESERVA_RENDA_FAMILIAR,IN_CONCLUINTE,ANO_INGRESSO,IDADE_INGRESSO
0,2,1,integral,1.0,1,1,1988,11,9,2008-01-01,NaN,NaN,0,2008,20
1,2,1,integral,1.0,1,2,1987,12,1,2007-01-01,NaN,NaN,0,2007,20
2,2,1,integral,1.0,1,1,1989,12,13,2009-01-01,0.0,0.0,1,2009,20
3,2,1,integral,1.0,1,2,1989,9,20,2010-01-01,NaN,NaN,0,2010,21
4,2,1,integral,1.0,1,1,1994,6,1,2013-01-01,NaN,NaN,1,2013,19
5,2,1,integral,1.0,1,2,1993,9,13,2011-01-01,NaN,NaN,0,2011,18
6,2,1,integral,1.0,1,1,1993,2,27,2011-01-01,NaN,NaN,1,2011,18
7,2,1,integral,1.0,1,1,1992,6,18,2011-01-01,0.0,0.0,0,2011,19
8,2,1,integral,1.0,1,1,1993,12,17,2011-01-01,NaN,NaN,1,2011,18
9,2,1,integral,1.0,1,2,1990,11,21,2011-01-01,0.0,0.0,1,2011,21
10,2,1,integral,1.0,1,1,1990,2,23,2011-01-01,0.0,0.0,1,2011,21
11,2,1,integral,1.0,1,2,1993,6,4,2013-01-01,0.0,0.0,0,2013,20
12,2,1,integral,1.0,1,1,1992,8,6,2012-01-01,NaN,NaN,1,2012,20
13,2,1,integral,1.0,2,2,1992,12,11,2016-01-01,1.0,0.0,0,2016,24
14,2,1,integral,1.0,1,1,1994,6,24,2014-01-01,NaN,NaN,0,2014,20
15,2,1,integral,1.0,4,2,1994,9,13,2014-01-01,0.0,0.0,0,2014,20
16,2,1,integral,1.0,1,1,1992,3,29,2012-01-01,0.0,0.0,1,2012,20
17,2,1,integral,1.0,1,1,1993,10,16,2012-01-01,NaN,NaN,1,2012,19
18,2,1,integral,1.0,4,1,1992,5,30,2012-01-01,0.0,0.0,1,2012,20
19,2,1,integral,1.0,1,1,1994,4,29,2012-01-01,NaN,NaN,0,2012,18
20,2,1,integral,1.0,4,1,1994,7,31,2012-01-01,NaN,NaN,1,2012,18
21,2,1,integral,1.0,1,2,1994,2,3,2012-01-01,NaN,NaN,1,2012,18
22,2,1,integral,1.0,1,1,1993,7,4,2012-01-01,0.0,0.0,1,2012,19
23,2,1,integral,1.0,1,1,1991,4,10,2012-01-01,NaN,NaN,0,2012,21
24,2,1,integral,1.0,3,1,1993,12,5,2012-01-01,1.0,0.0,0,2012,19
25,2,1,integral,1.0,4,1,1994,3,24,2012-01-01,NaN,NaN,1,2012,18
26,2,1,integral,1.0,1,1,1992,10,5,2012-01-01,NaN,NaN,1,2012,20
27,2,1,integral,1.0,4,1,1993,10,15,2012-01-01,NaN,NaN,1,2012,19
28,2,1,integral,1.0,1,1,1993,10,22,2012-01-01,NaN,NaN,1,2012,19
29,2,1,integral,1.0,1,2,1993,10,27,2012-01-01,NaN,NaN,0,2012,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791348,2,3,noturno,3.0,1,2,1995,2,3,2017-07-01,0.0,0.0,0,2017,22
791349,2,3,noturno,3.0,1,2,1994,9,1,2017-07-01,NaN,NaN,0,2017,23
791350,2,3,noturno,3.0,3,2,1983,11,3,2017-07-01,0.0,0.0,0,2017,34
791351,2,3,noturno,3.0,1,2,1995,9,4,2017-07-01,NaN,NaN,0,2017,22
791352,2,3,noturno,3.0,0,2,1997,3,17,2017-07-01,0.0,0.0,0,2017,20
791353,2,3,noturno,3.0,3,2,1999,11,6,2017-07-01,1.0,0.0,0,2017,18
791354,2,3,noturno,3.0,3,1,1991,2,7,2017-07-01,0.0,0.0,0,2017,26
791355,2,3,noturno,3.0,3,2,1974,12,16,2017-07-01,1.0,0.0,0,2017,43
791356,2,3,noturno,3.0,1,1,1983,7,1,2017-07-01,0.0,0.0,0,2017,34
791357,2,3,noturno,3.0,1,2,1990,8,15,2017-07-01,0.0,0.0,0,2017,27
791358,2,3,noturno,3.0,1,1,1981,7,23,2017-07-01,NaN,NaN,0,2017,36
791359,2,3,noturno,3.0,1,1,1992,12,22,2017-07-01,0.0,0.0,0,2017,25
791360,2,3,noturno,3.0,1,2,1986,10,21,2017-07-01,0.0,0.0,0,2017,31
791361,2,3,noturno,3.0,2,1,1980,2,1,2017-07-01,0.0,0.0,0,2017,37
791362,2,3,noturno,3.0,1,2,1994,7,13,2017-07-01,0.0,0.0,0,2017,23
791363,2,3,noturno,3.0,1,2,1985,10,12,2017-07-01,0.0,0.0,0,2017,32
791364,2,3,noturno,3.0,1,1,1981,3,19,2017-07-01,0.0,0.0,0,2017,36
791365,2,3,noturno,3.0,1,2,1993,6,4,2017-07-01,0.0,0.0,0,2017,24
791366,2,3,noturno,3.0,1,1,1996,12,28,2017-07-01,0.0,0.0,0,2017,21
791367,2,3,noturno,3.0,1,1,1997,10,16,2017-07-01,0.0,0.0,0,2017,20
791368,2,3,noturno,3.0,1,2,1998,10,6,2017-07-01,0.0,0.0,0,2017,19
791369,2,3,noturno,3.0,1,2,1983,7,17,2017-07-01,0.0,0.0,0,2017,34
791370,2,3,noturno,3.0,1,2,1977,2,26,2017-07-01,0.0,0.0,0,2017,40
791371,2,3,noturno,3.0,1,2,1962,7,28,2017-07-01,0.0,0.0,0,2017,55
791372,2,3,noturno,3.0,1,2,1971,10,13,2017-07-01,0.0,0.0,0,2017,46
791373,2,3,noturno,3.0,1,2,1968,7,26,2017-07-01,0.0,0.0,0,2017,49
791374,2,3,noturno,3.0,3,2,1995,7,23,2017-07-01,0.0,0.0,0,2017,22
791375,2,3,noturno,3.0,1,1,1998,6,11,2017-07-01,0.0,0.0,0,2017,19
791376,2,3,noturno,3.0,1,2,1973,3,15,2017-07-01,0.0,0.0,0,2017,44
791377,2,3,noturno,3.0,1,2,1994,10,8,2017-07-01,0.0,0.0,0,2017,23

#### IDADE_INGRESSO

In [11]:
df['IDADE_INGRESSO_N'] = df['IDADE_INGRESSO'].apply(lambda x: 'MENOR_19' if x<19 else('MENOR_23' if x <23 else('MENOR_27' if x < 27 else('MAIOR_27') )))

#### SEXO

In [17]:
df['SEXO_N'] = df['TP_SEXO'].apply(lambda x: 'FEMININO' if x == 1 else('MASCULINO'))

#### ETNIA

In [20]:
df['ETNIA_N'] = df['TP_COR_RACA'].apply(lambda x: 'BRANCA' if x == 1 else('PRETA' if x == 2 else('PARDA' if x == 3 else('AMARELA' if x == 4 else('INDIGENA' if x == 5 else('NAO_DECLARADO'))))))

#### IN_RESERVA_ETNICO

In [21]:
df['IN_RESERVA_ETNICO_N'] = df['IN_RESERVA_ETNICO'].apply(lambda x: 'SIM' if x == 1 else('NAO'))

#### IN_RESERVA_RENDA_FAMILIAR

In [22]:
df['IN_RESERVA_RENDA_FAMILIAR_N'] = df['IN_RESERVA_RENDA_FAMILIAR'].apply(lambda x: 'SIM' if x == 1 else('NAO'))

#### CONCLUINTE

In [24]:
df['CONCLUINTE_N'] = df['IN_CONCLUINTE'].apply(lambda x: 'SIM' if x == 1 else('NAO'))

In [25]:
df

,TP_CATEGORIA_ADMINISTRATIVA,TP_ORGANIZACAO_ACADEMICA,TP_TURNO,TP_GRAU_ACADEMICO,TP_COR_RACA,TP_SEXO,NU_ANO_NASCIMENTO,NU_MES_NASCIMENTO,NU_DIA_NASCIMENTO,DT_INGRESSO_CURSO,...,IN_RESERVA_RENDA_FAMILIAR,IN_CONCLUINTE,ANO_INGRESSO,IDADE_INGRESSO,IDADE_INGRESSO_N,IN_RESERVA_ETNICO_N,IN_RESERVA_RENDA_FAMILIAR_N,SEXO_N,ETNIA_N,CONCLUINTE_N
0,2,1,integral,1.0,1,1,1988,11,9,2008-01-01,...,NaN,0,2008,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
1,2,1,integral,1.0,1,2,1987,12,1,2007-01-01,...,NaN,0,2007,20,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
2,2,1,integral,1.0,1,1,1989,12,13,2009-01-01,...,0.0,1,2009,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
3,2,1,integral,1.0,1,2,1989,9,20,2010-01-01,...,NaN,0,2010,21,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
4,2,1,integral,1.0,1,1,1994,6,1,2013-01-01,...,NaN,1,2013,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
5,2,1,integral,1.0,1,2,1993,9,13,2011-01-01,...,NaN,0,2011,18,MENOR_19,NAO,NAO,MASCULINO,BRANCA,NAO
6,2,1,integral,1.0,1,1,1993,2,27,2011-01-01,...,NaN,1,2011,18,MENOR_19,NAO,NAO,FEMININO,BRANCA,SIM
7,2,1,integral,1.0,1,1,1992,6,18,2011-01-01,...,0.0,0,2011,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
8,2,1,integral,1.0,1,1,1993,12,17,2011-01-01,...,NaN,1,2011,18,MENOR_19,NAO,NAO,FEMININO,BRANCA,SIM
9,2,1,integral,1.0,1,2,1990,11,21,2011-01-01,...,0.0,1,2011,21,MENOR_23,NAO,NAO,MASCULINO,BRANCA,SIM
10,2,1,integral,1.0,1,1,1990,2,23,2011-01-01,...,0.0,1,2011,21,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
11,2,1,integral,1.0,1,2,1993,6,4,2013-01-01,...,0.0,0,2013,20,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
12,2,1,integral,1.0,1,1,1992,8,6,2012-01-01,...,NaN,1,2012,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
13,2,1,integral,1.0,2,2,1992,12,11,2016-01-01,...,0.0,0,2016,24,MENOR_27,SIM,NAO,MASCULINO,PRETA,NAO
14,2,1,integral,1.0,1,1,1994,6,24,2014-01-01,...,NaN,0,2014,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
15,2,1,integral,1.0,4,2,1994,9,13,2014-01-01,...,0.0,0,2014,20,MENOR_23,NAO,NAO,MASCULINO,AMARELA,NAO
16,2,1,integral,1.0,1,1,1992,3,29,2012-01-01,...,0.0,1,2012,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
17,2,1,integral,1.0,1,1,1993,10,16,2012-01-01,...,NaN,1,2012,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
18,2,1,integral,1.0,4,1,1992,5,30,2012-01-01,...,0.0,1,2012,20,MENOR_23,NAO,NAO,FEMININO,AMARELA,SIM
19,2,1,integral,1.0,1,1,1994,4,29,2012-01-01,...,NaN,0,2012,18,MENOR_19,NAO,NAO,FEMININO,BRANCA,NAO
20,2,1,integral,1.0,4,1,1994,7,31,2012-01-01,...,NaN,1,2012,18,MENOR_19,NAO,NAO,FEMININO,AMARELA,SIM
21,2,1,integral,1.0,1,2,1994,2,3,2012-01-01,...,NaN,1,2012,18,MENOR_19,NAO,NAO,MASCULINO,BRANCA,SIM
22,2,1,integral,1.0,1,1,1993,7,4,2012-01-01,...,0.0,1,2012,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
23,2,1,integral,1.0,1,1,1991,4,10,2012-01-01,...,NaN,0,2012,21,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
24,2,1,integral,1.0,3,1,1993,12,5,2012-01-01,...,0.0,0,2012,19,MENOR_23,SIM,NAO,FEMININO,PARDA,NAO
25,2,1,integral,1.0,4,1,1994,3,24,2012-01-01,...,NaN,1,2012,18,MENOR_19,NAO,NAO,FEMININO,AMARELA,SIM
26,2,1,integral,1.0,1,1,1992,10,5,2012-01-01,...,NaN,1,2012,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
27,2,1,integral,1.0,4,1,1993,10,15,2012-01-01,...,NaN,1,2012,19,MENOR_23,NAO,NAO,FEMININO,AMARELA,SIM
28,2,1,integral,1.0,1,1,1993,10,22,2012-01-01,...,NaN,1,2012,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,SIM
29,2,1,integral,1.0,1,2,1993,10,27,2012-01-01,...,NaN,0,2012,19,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791348,2,3,noturno,3.0,1,2,1995,2,3,2017-07-01,...,0.0,0,2017,22,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
791349,2,3,noturno,3.0,1,2,1994,9,1,2017-07-01,...,NaN,0,2017,23,MENOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791350,2,3,noturno,3.0,3,2,1983,11,3,2017-07-01,...,0.0,0,2017,34,MAIOR_27,NAO,NAO,MASCULINO,PARDA,NAO
791351,2,3,noturno,3.0,1,2,1995,9,4,2017-07-01,...,NaN,0,2017,22,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
791352,2,3,noturno,3.0,0,2,1997,3,17,2017-07-01,...,0.0,0,2017,20,MENOR_23,NAO,NAO,MASCULINO,NAO_DECLARADO,NAO
791353,2,3,noturno,3.0,3,2,1999,11,6,2017-07-01,...,0.0,0,2017,18,MENOR_19,SIM,NAO,MASCULINO,PARDA,NAO
791354,2,3,noturno,3.0,3,1,1991,2,7,2017-07-01,...,0.0,0,2017,26,MENOR_27,NAO,NAO,FEMININO,PARDA,NAO
791355,2,3,noturno,3.0,3,2,1974,12,16,2017-07-01,...,0.0,0,2017,43,MAIOR_27,SIM,NAO,MASCULINO,PARDA,NAO
791356,2,3,noturno,3.0,1,1,1983,7,1,2017-07-01,...,0.0,0,2017,34,MAIOR_27,NAO,NAO,FEMININO,BRANCA,NAO
791357,2,3,noturno,3.0,1,2,1990,8,15,2017-07-01,...,0.0,0,2017,27,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791358,2,3,noturno,3.0,1,1,1981,7,23,2017-07-01,...,NaN,0,2017,36,MAIOR_27,NAO,NAO,FEMININO,BRANCA,NAO
791359,2,3,noturno,3.0,1,1,1992,12,22,2017-07-01,...,0.0,0,2017,25,MENOR_27,NAO,NAO,FEMININO,BRANCA,NAO
791360,2,3,noturno,3.0,1,2,1986,10,21,2017-07-01,...,0.0,0,2017,31,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791361,2,3,noturno,3.0,2,1,1980,2,1,2017-07-01,...,0.0,0,2017,37,MAIOR_27,NAO,NAO,FEMININO,PRETA,NAO
791362,2,3,noturno,3.0,1,2,1994,7,13,2017-07-01,...,0.0,0,2017,23,MENOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791363,2,3,noturno,3.0,1,2,1985,10,12,2017-07-01,...,0.0,0,2017,32,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791364,2,3,noturno,3.0,1,1,1981,3,19,2017-07-01,...,0.0,0,2017,36,MAIOR_27,NAO,NAO,FEMININO,BRANCA,NAO
791365,2,3,noturno,3.0,1,2,1993,6,4,2017-07-01,...,0.0,0,2017,24,MENOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791366,2,3,noturno,3.0,1,1,1996,12,28,2017-07-01,...,0.0,0,2017,21,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
791367,2,3,noturno,3.0,1,1,1997,10,16,2017-07-01,...,0.0,0,2017,20,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
791368,2,3,noturno,3.0,1,2,1998,10,6,2017-07-01,...,0.0,0,2017,19,MENOR_23,NAO,NAO,MASCULINO,BRANCA,NAO
791369,2,3,noturno,3.0,1,2,1983,7,17,2017-07-01,...,0.0,0,2017,34,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791370,2,3,noturno,3.0,1,2,1977,2,26,2017-07-01,...,0.0,0,2017,40,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791371,2,3,noturno,3.0,1,2,1962,7,28,2017-07-01,...,0.0,0,2017,55,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791372,2,3,noturno,3.0,1,2,1971,10,13,2017-07-01,...,0.0,0,2017,46,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791373,2,3,noturno,3.0,1,2,1968,7,26,2017-07-01,...,0.0,0,2017,49,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791374,2,3,noturno,3.0,3,2,1995,7,23,2017-07-01,...,0.0,0,2017,22,MENOR_23,NAO,NAO,MASCULINO,PARDA,NAO
791375,2,3,noturno,3.0,1,1,1998,6,11,2017-07-01,...,0.0,0,2017,19,MENOR_23,NAO,NAO,FEMININO,BRANCA,NAO
791376,2,3,noturno,3.0,1,2,1973,3,15,2017-07-01,...,0.0,0,2017,44,MAIOR_27,NAO,NAO,MASCULINO,BRANCA,NAO
791377,2,3,noturno,3.0,1,2,1994,10,8,2017-07-01,...,0.0,0,2017,23,MENOR_27,NAO,NAO,MASCULINO,BRANCA,NAO

In [47]:
df2 = pd.read_csv('DM_ALUNO.csv', sep='|', nrows=500)
list(df2)

['NU_ANO_CENSO',
 'CO_IES',
 'TP_CATEGORIA_ADMINISTRATIVA',
 'TP_ORGANIZACAO_ACADEMICA',
 'CO_CURSO',
 'CO_CURSO_POLO',
 'TP_TURNO',
 'TP_GRAU_ACADEMICO',
 'TP_MODALIDADE_ENSINO',
 'TP_NIVEL_ACADEMICO',
 'CO_OCDE_AREA_GERAL',
 'CO_OCDE_AREA_ESPECIFICA',
 'CO_OCDE_AREA_DETALHADA',
 'CO_OCDE',
 'CO_ALUNO',
 'CO_ALUNO_CURSO',
 'CO_ALUNO_CURSO_ORIGEM',
 'TP_COR_RACA',
 'TP_SEXO',
 'NU_ANO_NASCIMENTO',
 'NU_MES_NASCIMENTO',
 'NU_DIA_NASCIMENTO',
 'NU_IDADE',
 'TP_NACIONALIDADE',
 'CO_PAIS_ORIGEM',
 'CO_UF_NASCIMENTO',
 'CO_MUNICIPIO_NASCIMENTO',
 'TP_DEFICIENCIA',
 'IN_DEFICIENCIA_AUDITIVA',
 'IN_DEFICIENCIA_FISICA',
 'IN_DEFICIENCIA_INTELECTUAL',
 'IN_DEFICIENCIA_MULTIPLA',
 'IN_DEFICIENCIA_SURDEZ',
 'IN_DEFICIENCIA_SURDOCEGUEIRA',
 'IN_DEFICIENCIA_BAIXA_VISAO',
 'IN_DEFICIENCIA_CEGUEIRA',
 'IN_DEFICIENCIA_SUPERDOTACAO',
 'IN_TGD_AUTISMO_INFANTIL',
 'IN_TGD_SINDROME_ASPERGER',
 'IN_TGD_SINDROME_RETT',
 'IN_TGD_TRANSTOR_DESINTEGRATIVO',
 'TP_SITUACAO',
 'QT_CARGA_HORARIA_TOTAL',
 'QT_CARGA_HORARIA_INTEG',
 'DT_INGRESSO_CURSO',
 'IN_INGRESSO_VESTIBULAR',
 'IN_INGRESSO_ENEM',
 'IN_INGRESSO_AVALIACAO_SERIADA',
 'IN_INGRESSO_SELECAO_SIMPLIFICA',
 'IN_INGRESSO_OUTRO_TIPO_SELECAO',
 'IN_INGRESSO_VAGA_REMANESC',
 'IN_INGRESSO_VAGA_PROG_ESPECIAL',
 'IN_INGRESSO_TRANSF_EXOFFICIO',
 'IN_INGRESSO_DECISAO_JUDICIAL',
 'IN_INGRESSO_CONVENIO_PECG',
 'IN_INGRESSO_EGRESSO',
 'IN_INGRESSO_OUTRA_FORMA',
 'IN_RESERVA_VAGAS',
 'IN_RESERVA_ETNICO',
 'IN_RESERVA_DEFICIENCIA',
 'IN_RESERVA_ENSINO_PUBLICO',
 'IN_RESERVA_RENDA_FAMILIAR',
 'IN_RESERVA_OUTRA',
 'IN_FINANCIAMENTO_ESTUDANTIL',
 'IN_FIN_REEMB_FIES',
 'IN_FIN_REEMB_ESTADUAL',
 'IN_FIN_REEMB_MUNICIPAL',
 'IN_FIN_REEMB_PROG_IES',
 'IN_FIN_REEMB_ENT_EXTERNA',
 'IN_FIN_REEMB_OUTRA',
 'IN_FIN_NAOREEMB_PROUNI_INTEGR',
 'IN_FIN_NAOREEMB_PROUNI_PARCIAL',
 'IN_FIN_NAOREEMB_ESTADUAL',
 'IN_FIN_NAOREEMB_MUNICIPAL',
 'IN_FIN_NAOREEMB_PROG_IES',
 'IN_FIN_NAOREEMB_ENT_EXTERNA',
 'IN_FIN_NAOREEMB_OUTRA',
 'IN_APOIO_SOCIAL',
 'IN_APOIO_ALIMENTACAO',
 'IN_APOIO_BOLSA_PERMANENCIA',
 'IN_APOIO_BOLSA_TRABALHO',
 'IN_APOIO_MATERIAL_DIDATICO',
 'IN_APOIO_MORADIA',
 'IN_APOIO_TRANSPORTE',
 'IN_ATIVIDADE_EXTRACURRICULAR',
 'IN_COMPLEMENTAR_ESTAGIO',
 'IN_COMPLEMENTAR_EXTENSAO',
 'IN_COMPLEMENTAR_MONITORIA',
 'IN_COMPLEMENTAR_PESQUISA',
 'IN_BOLSA_ESTAGIO',
 'IN_BOLSA_EXTENSAO',
 'IN_BOLSA_MONITORIA',
 'IN_BOLSA_PESQUISA',
 'TP_ESCOLA_CONCLUSAO_ENS_MEDIO',
 'IN_ALUNO_PARFOR',
 'TP_SEMESTRE_CONCLUSAO',
 'TP_SEMESTRE_REFERENCIA',
 'IN_MOBILIDADE_ACADEMICA',
 'TP_MOBILIDADE_ACADEMICA',
 'TP_MOBILIDADE_ACADEMICA_INTERN',
 'CO_IES_DESTINO',
 'CO_PAIS_DESTINO',
 'IN_MATRICULA',
 'IN_CONCLUINTE',
 'IN_INGRESSO_TOTAL',
 'IN_INGRESSO_VAGA_NOVA',
 'IN_INGRESSO_PROCESSO_SELETIVO',
 'NU_ANO_INGRESSO']

#### Eliminando os atributos numéricos que foram usados para transformação

In [33]:
df.drop(['TP_GRAU_ACADEMICO', 'TP_CATEGORIA_ADMINISTRATIVA', 'TP_ORGANIZACAO_ACADEMICA', 'DT_INGRESSO_CURSO', 'IDADE_INGRESSO', 'TP_SEXO', 'TP_COR_RACA', 'IN_RESERVA_ETNICO', 'IN_RESERVA_RENDA_FAMILIAR', 'IN_CONCLUINTE', 'NU_MES_NASCIMENTO', 'NU_DIA_NASCIMENTO', 'NU_ANO_NASCIMENTO', 'ANO_INGRESSO'], axis=1, inplace=True)

#### Exportando a base transformada

In [38]:
df.to_csv('alunos_done.CSV', sep=',', index=None)